word = "guglbon"
type = "cmevla"
rafsi = []
selmaho = []
created = "2009-11-02T21:48:59Z"
creator = "sarefo"
source_ids = ["valsi=9766"]

[[etymology]]
id = 169
lang = "en"
author = "sarefo"
updated = "2009-11-02T21:49:50Z"
content = "From Google + boxna rafsi -bon-."
