word = "plisyjisra"
type = "lujvo"
rafsi = []
selmaho = []
created = "2013-08-07T14:17:41Z"
creator = "Wuzzy"
source_ids = ["valsi=17533"]

[[etymology]]
id = 288
lang = "de"
author = "Wuzzy"
updated = "2013-08-07T14:20:57Z"
content = "Aus dem veljvo »plise jisra«."

[[etymology]]
id = 289
lang = "en"
author = "Wuzzy"
updated = "2013-08-07T14:21:16Z"
content = "From veljvo “plise jisra”."

[[etymology]]
id = 290
lang = "jbo"
author = "Wuzzy"
updated = "2013-08-07T14:23:24Z"
content = "finti fo lo veljvo po'u lu plise jisra li'u"
