word = "pamrkovni"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2014-07-21T07:57:05Z"
creator = "gleki"
source_ids = ["valsi=27150"]

[[etymology]]
id = 552
lang = "en"
author = "gleki"
updated = "2014-09-06T04:58:38Z"
content = "zoi by.памяркоуный.by. valsi lo pamrkovni lo banbu'elu"
