word = "rakle"
type = "experimental gismu"
rafsi = []
selmaho = []
created = "2014-06-16T07:04:44Z"
creator = "krtisfranks"
source_ids = ["valsi=26864"]

[[etymology]]
id = 475
lang = "en"
author = "krtisfranks"
updated = "2014-06-16T07:06:21Z"
content = "{ratni}+{klesi}"
