word = "grosela"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2014-07-06T15:54:04Z"
creator = "gleki"
source_ids = ["valsi=27082"]

[[etymology]]
id = 530
lang = "en"
author = "gleki"
updated = "2014-07-06T15:55:07Z"
content = "lo simsa be zo grosela cu valsi lo grosela lo so'i latmo krasi bangu"
