word = "caxmati"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2003-03-09T03:31:43Z"
creator = "phma"
source_ids = ["valsi=2477"]

[[etymology]]
id = 62
lang = "en"
author = "Yanis"
updated = "2006-05-13T06:55:06Z"
content = "From Russian шахматы (chess)"
