word = "tartaruga"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-09-07T07:48:25Z"
creator = "gleki"
source_ids = ["valsi=29803"]

[[etymology]]
id = 901
lang = "en"
author = "gleki"
updated = "2015-09-07T11:08:19Z"
content = "zoi .vric.tartaruga.vric. valsi zo tartaruga lo baurgulugu .e lo bangitu'a .e lo banpu'oru"
