word = "gunka"
type = "gismu"
rafsi = ["gu'a", "gun", "gunk"]
selmaho = []
created = "2003-03-03T01:36:56Z"
creator = "noralujv"
source_ids = ["valsi=420"]

[[etymology]]
id = 243
lang = "zh"
author = "mxx"
updated = "2013-01-06T15:30:43Z"
content = "Chinese: gun — 工 [gōng];English: urk — work; Hindi: kam — काम [kāma]\r\n"
