source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=zantufa+jonma%27o"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "102b93bc10b6160ab1b6707cee8592cdbd26a5e0e4679c7089e4ca4c9ad38e74"
bytes = 1317997
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2015-07-08T02:21:15Z"
to = "2016-07-04T05:01:23Z"

[coverage.counts]
"pages" = 1
"revisions" = 20
