source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=File%3ANeck.agr.jpg"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "ade3bd85c535fea0b4c3c745256d11a1fa7aa9d312724a9e5c27cf2c809f4467"
bytes = 576
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2016-04-19T09:38:21Z"
to = "2016-04-19T09:38:21Z"

[coverage.counts]
"pages" = 1
"revisions" = 1
