source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=File%3ABucket.agr.jpg"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "0e47d22e788a7a7f7672d886f1c972e83ae51c54fdecb295981a8da6d982803f"
bytes = 578
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2016-04-19T09:27:36Z"
to = "2016-04-19T09:27:36Z"

[coverage.counts]
"pages" = 1
"revisions" = 1
