source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=File%3AGnome-mime-application-pdf.svg"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "27c7b0a6f8b42cd714c38ab12cac10aafdbcc6b71840ff9330fa2dc762da8351"
bytes = 669
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2013-12-17T07:05:42Z"
to = "2013-12-17T07:05:42Z"

[coverage.counts]
"pages" = 1
"revisions" = 1
