source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=File%3A1366897730884.gif"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "e5acdd26f1677151661e8ffd37d120b5ecc139e5f5033dbe0b10745b0160f9fb"
bytes = 841
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2013-11-04T17:38:32Z"
to = "2013-11-04T17:39:21Z"

[coverage.counts]
"pages" = 1
"revisions" = 2
