source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=MediaWiki%3ABw-sidebar-news%2Fshi"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "0d9376b4f574f73e43d33664afed12d7875b9d1c6da52b16c1f196b5d939bf8b"
bytes = 595
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2014-09-22T09:48:19Z"
to = "2014-09-22T09:48:19Z"

[coverage.counts]
"pages" = 1
"revisions" = 1
