source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvcontinue=20140617124002%7C96677&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=L17-01"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "3893f7c7a4830efbb70838a6ed1280f439ea127a70119a3782f164994ba799db"
bytes = 8334989
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2014-06-17T12:40:02Z"
to = "2014-06-27T17:45:50Z"

[coverage.counts]
"pages" = 1
"revisions" = 30
