source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=MediaWiki%3ATranslate-js-support-unsaved-warning%2Fja"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "716ab9ecb30c0a39b84917c77d3f523daa069a1d10789617e333624f452cc81a"
bytes = 662
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2014-07-26T19:17:55Z"
to = "2014-07-26T19:17:55Z"

[coverage.counts]
"pages" = 1
"revisions" = 1
