source = "wiki"
kind = "revisions"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&maxlag=5&prop=revisions%7Cinfo&rvdir=newer&rvlimit=max&rvprop=ids%7Ctimestamp%7Cuser%7Cuserid%7Ccomment%7Csize%7Csha1%7Ccontent%7Cflags&rvslots=main&titles=File%3Aviewtool-src.tar.gz"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "50e73c1cd88380d5bef06c282b254eeb1a9a220c8634bf7ff59ca66e9dea7ad6"
bytes = 965
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2013-11-04T17:18:20Z"
to = "2013-11-21T05:51:42Z"

[coverage.counts]
"pages" = 1
"revisions" = 2
