source = "wiki"
kind = "logevents"
origin = "https://mw.lojban.org/api.php?action=query&format=json&formatversion=2&lecontinue=20140630082619%7C61820&ledir=newer&lelimit=max&leprop=ids%7Ctitle%7Ctype%7Cuser%7Ctimestamp%7Ccomment%7Cdetails&letype=move&list=logevents&maxlag=5"
fetched_at = 2026-09-14T11:27:25+00:00
sha256 = "6c9e3b414fba30e5e0c4d4f800080b1d316fe16ea0a063c296518ede683d9933"
bytes = 169248
notes = "MediaWiki API formatversion=2"

[coverage]
from = "2014-06-30T08:26:19Z"
to = "2014-06-30T08:39:18Z"

[coverage.counts]
"logevents" = 500
