word = "karkade"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2005-01-13T05:51:46Z"
creator = "phma"
source_ids = ["valsi=8562"]

[[etymology]]
id = 69
lang = "en"
author = "phma"
updated = "2006-11-29T15:33:18Z"
content = "Arabic كركديه karkade (Egyptian dialect), karkadia"
