word = "iolna"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-07-02T15:42:47Z"
creator = "spheniscine"
source_ids = ["valsi=29192"]

[[etymology]]
id = 799
lang = "en"
author = "spheniscine"
updated = "2015-07-02T15:43:56Z"
content = "Lojban {io} + {nanmu}"
