word = "altaisakta"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2016-09-09T16:10:34Z"
creator = "lin"
source_ids = ["valsi=30709"]

[[etymology]]
id = 1128
lang = "en"
author = "lin"
updated = "2016-09-09T16:13:19Z"
content = "{sparaltaia} + {sakta}"
