word = "sifnaptera"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2009-10-02T23:26:36Z"
creator = "sarefo"
source_ids = ["valsi=9718"]

[[etymology]]
id = 163
lang = "en"
author = "sarefo"
updated = "2009-10-02T23:27:41Z"
content = "From order Siphonaptera."
