word = "frisefa"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-08-31T19:24:07Z"
creator = "zozeizeizeizeifaho"
source_ids = ["valsi=29781"]

[[etymology]]
id = 895
lang = "en"
author = "spheniscine"
updated = "2015-09-01T07:55:59Z"
content = "Lojban {lifri} + {se fanta}"
