word = "djumxuriia"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-08-12T09:51:49Z"
creator = "gleki"
source_ids = ["valsi=29637"]

[[etymology]]
id = 1712
lang = "en"
author = "phma"
updated = "2022-12-06T17:26:08Z"
content = "Arabic جمهورية"
