source = "irc/lojban"
kind = "apache-index"
origin = "https://lojban.org/irclogs/lojban/2007_11/"
fetched_at = 2026-09-16T14:07:03+00:00
sha256 = "fc11e1532f68582f37f3ddf5c18dbef23765e26f938a78bbc3dcc384c47711d6"
bytes = 7498
notes = "lojban/2007_11/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 29
