source = "irc/lojban"
kind = "apache-index"
origin = "https://lojban.org/irclogs/lojban/2002_12/"
fetched_at = 2026-09-16T13:44:28+00:00
sha256 = "4f9754d35d8acad9c1a2ed4726febcebdb3c2130445d9b3b878d991558ce433e"
bytes = 2418
notes = "lojban/2002_12/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 6
