source = "irc/lojban"
kind = "apache-index"
origin = "https://lojban.org/irclogs/lojban/2019_10/"
fetched_at = 2026-09-16T15:13:02+00:00
sha256 = "9ac6532f902fe5f22a16abb5b41bcc4cf3d41c2627faa82226f8ae1d5524aeaf"
bytes = 7324
notes = "lojban/2019_10/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 29
