source = "irc/lojban"
kind = "apache-index"
origin = "https://lojban.org/irclogs/lojban/2003_02/"
fetched_at = 2026-09-16T13:44:28+00:00
sha256 = "8197a6df12727a4ba1d6912e3e43fa71d1036b0dd073bd4c6f43840ff32650ee"
bytes = 7277
notes = "lojban/2003_02/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 28
