source = "irc/lojban"
kind = "apache-index"
origin = "https://lojban.org/irclogs/lojban/2003_03/"
fetched_at = 2026-09-16T13:44:28+00:00
sha256 = "27ec760addeb13aeaef09fddb6778df300c9276444bd998e15a1b9d1b9d6d311"
bytes = 7940
notes = "lojban/2003_03/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 31
