word = "ni'a'au"
type = "experimental cmavo"
rafsi = []
selmaho = ["GAhUhAU"]
created = "2015-04-17T04:28:46Z"
creator = "krtisfranks"
source_ids = ["valsi=28589"]

[[etymology]]
id = 679
lang = "en"
author = "krtisfranks"
updated = "2015-04-17T04:29:50Z"
content = "{cnita}"
