word = "bamrti'enti"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-05-31T15:31:37Z"
creator = "Wuzzy"
source_ids = ["valsi=28813"]

[[etymology]]
id = 712
lang = "en"
author = "Wuzzy"
updated = "2015-05-31T15:32:01Z"
content = "From English pronunciation of “TNT”."
