word = "ka'o'ei"
type = "experimental cmavo"
rafsi = []
selmaho = []
created = "2014-12-26T05:27:53Z"
creator = "krtisfranks"
source_ids = ["valsi=27910"]

[[etymology]]
id = 1229
lang = "en"
author = "krtisfranks"
updated = "2017-03-31T23:01:11Z"
content = "{ka'o} + \"e\" for the number e ({te'o}) + \"i\" for the imaginary unit i"
