word = "tsukate"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-03-18T13:47:54Z"
creator = "gleki"
source_ids = ["valsi=28503"]

[[etymology]]
id = 830
lang = "en"
author = "gleki"
updated = "2015-07-12T15:31:29Z"
content = "zoi ry.цукат.ry.noi du zoi gy.tsukat.gy. valsi lo tsukata lo rusko"
