word = "sarnyskrantykemyzgitci"
type = "lujvo"
rafsi = []
selmaho = []
created = "2016-04-10T08:43:16Z"
creator = "krtisfranks"
source_ids = ["valsi=30477"]

[[etymology]]
id = 1050
lang = "en"
author = "krtisfranks"
updated = "2016-04-10T08:44:24Z"
content = "{sarni} + {skrante} + {ke} + {zgitci}"
