word = "kesri"
type = "experimental gismu"
rafsi = ["kesr"]
selmaho = []
created = "2015-06-25T17:17:13Z"
creator = "ctefaho"
source_ids = ["valsi=29080"]

[[etymology]]
id = 792
lang = "en"
author = "ahernai"
updated = "2015-06-29T09:53:46Z"
content = "python gismu_score.py -s ccvcv,cvccv kebaniinsian steriiotaip tksali estereotip stereotip suranamatiia"
