word = "xlatsu'aci"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2022-04-04T20:31:24Z"
creator = "viktor"
source_ids = ["valsi=34114"]

[[etymology]]
id = 1659
lang = "en"
author = "viktor"
updated = "2022-04-04T20:31:49Z"
content = "Japanese yatsuhashi (八ツ橋 / 八橋)"
