word = "dansrbaleto"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2013-06-26T10:06:49Z"
creator = "jongausib"
source_ids = ["valsi=17155"]

[[etymology]]
id = 357
lang = "en"
author = "Wuzzy"
updated = "2013-10-20T21:12:39Z"
content = "The word “ballet” comes from the French. The French word in turn has its origin in Italian “balletto”."
