word = "fizde"
type = "experimental gismu"
rafsi = []
selmaho = []
created = "2016-01-17T21:27:38Z"
creator = "krtisfranks"
source_ids = ["valsi=30198"]

[[etymology]]
id = 966
lang = "en"
author = "krtisfranks"
updated = "2016-01-17T21:39:42Z"
content = "{fizbu} + {denpa}"
