source = "irc/jbosnu"
kind = "apache-index"
origin = "https://lojban.org/irclogs/jbosnu/2004_06/"
fetched_at = 2026-09-16T16:06:22+00:00
sha256 = "7535f737a8832c2bde2ff157a8fcf76ccffde845e6ff29b614958fdcba4c1103"
bytes = 7719
notes = "jbosnu/2004_06/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 30
