source = "irc/jbosnu"
kind = "apache-index"
origin = "https://lojban.org/irclogs/jbosnu/2022_12/"
fetched_at = 2026-09-16T21:59:25+00:00
sha256 = "e273f05eb47ec7eb55fb3194bdf0e1d0c330f310ddd28e8127707b43c655ca0b"
bytes = 3454
notes = "jbosnu/2022_12/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 11
