source = "irc/jbosnu"
kind = "apache-index"
origin = "https://lojban.org/irclogs/jbosnu/2018_09/"
fetched_at = 2026-09-16T21:59:25+00:00
sha256 = "ada3f5f12dc4d6e84918b1aa9c89449c44d3eaccfdbd71774bae482a24cbfd7d"
bytes = 5389
notes = "jbosnu/2018_09/"

[coverage]
from = "unknown"
to = "unknown"

[coverage.counts]
"files" = 20
