word = "jaurxarju"
type = "lujvo"
rafsi = []
selmaho = []
created = "2018-06-06T20:45:44Z"
creator = "phma"
source_ids = ["valsi=32346"]

[[etymology]]
id = 1464
lang = "en"
author = "phma"
updated = "2018-06-06T20:54:20Z"
content = "Calque of genus name Hydrochoerus, Arabic خِنْزِير الْمَاء‎‎, Chinese 水豚, Finnish vesisika, etc."
