word = "blabruk"
type = "cmevla"
rafsi = []
selmaho = []
created = "2003-03-09T16:19:35Z"
creator = "phma"
source_ids = ["valsi=2489"]

[[etymology]]
id = 155
lang = "en"
author = "sarefo"
updated = "2009-09-18T22:12:29Z"
content = "From {blabi} {rusko}."
