word = "mardeji"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-06-24T18:03:07Z"
creator = "krtisfranks"
source_ids = ["valsi=29054"]

[[etymology]]
id = 775
lang = "en"
author = "krtisfranks"
updated = "2015-06-24T18:03:36Z"
content = "{marde}+{jinvi}"
