word = "xonba"
type = "experimental gismu"
rafsi = []
selmaho = []
created = "2016-01-17T00:52:07Z"
creator = "krtisfranks"
source_ids = ["valsi=30191"]

[[etymology]]
id = 963
lang = "en"
author = "krtisfranks"
updated = "2016-01-17T00:53:17Z"
content = "Experimental rafsi \"-xon-\" (for {xo'ei}) + {xadba}"
