word = "viktsispa"
type = "lujvo"
rafsi = []
selmaho = []
created = "2004-06-17T05:40:34Z"
creator = "phma"
source_ids = ["valsi=8454"]

[[etymology]]
id = 30
lang = "en"
author = "phma"
updated = "2004-06-17T05:44:36Z"
content = "reverse calque: \"viscous\" is from Latin \"viscum\", mistletoe"
