word = "julro"
type = "experimental gismu"
rafsi = ["julr"]
selmaho = []
created = "2015-12-10T02:53:34Z"
creator = "krtisfranks"
source_ids = ["valsi=30099"]

[[etymology]]
id = 942
lang = "en"
author = "krtisfranks"
updated = "2015-12-10T03:08:50Z"
content = "{julra'o}"
