word = "kreivi"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-03-23T18:28:12Z"
creator = "gleki"
source_ids = ["valsi=28527"]

[[etymology]]
id = 665
lang = "en"
author = "gleki"
updated = "2015-03-23T18:31:18Z"
content = "se finti la gleki"
