word = "jmite"
type = "experimental gismu"
rafsi = ["jmit"]
selmaho = []
created = "2022-07-13T15:12:38Z"
creator = "janbe"
source_ids = ["valsi=34234"]

[[etymology]]
id = 1688
lang = "en"
author = "janbe"
updated = "2022-07-13T15:21:56Z"
content = "cf. Loglan \"jmite\" (KAO meets/encounters BEU)"
