word = "tcimbolo"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2012-10-22T15:56:01Z"
creator = "phma"
source_ids = ["valsi=15999"]

[[etymology]]
id = 238
lang = "en"
author = "phma"
updated = "2012-10-22T17:42:36Z"
content = "Spanish chimbolo"
