word = "lojyske"
type = "lujvo"
rafsi = []
selmaho = []
created = "2018-06-06T00:46:30Z"
creator = "Xabju"
source_ids = ["valsi=32276"]

[[etymology]]
id = 1453
lang = "en"
author = "Xabju"
updated = "2018-06-06T00:47:27Z"
content = "logji + saske"
