word = "lujyzba"
type = "lujvo"
rafsi = []
selmaho = []
created = "2016-06-05T12:38:58Z"
creator = "nielstron"
source_ids = ["valsi=30566"]

[[etymology]]
id = 1085
lang = "en"
author = "nielstron"
updated = "2016-06-05T12:41:13Z"
content = "rafsi of lujvo (luj) + glue hyphen (y) + rafsi of zbasu (zba)"
