word = "fe'oi"
type = "experimental cmavo"
rafsi = []
selmaho = ["COI"]
created = "2016-03-31T21:28:09Z"
creator = "krtisfranks"
source_ids = ["valsi=30446"]

[[etymology]]
id = 1033
lang = "en"
author = "krtisfranks"
updated = "2016-03-31T21:28:53Z"
content = "{fe'o} + French/Spanish: \"fin\"."
