word = "xadji"
type = "experimental gismu"
rafsi = []
selmaho = []
created = "2015-11-20T21:17:54Z"
creator = "krtisfranks"
source_ids = ["valsi=30049"]

[[etymology]]
id = 933
lang = "en"
author = "krtisfranks"
updated = "2015-11-20T21:18:27Z"
content = "{xance} + {degji}"
