word = "na'itfa"
type = "fu'ivla"
rafsi = []
selmaho = []
created = "2015-09-05T04:09:01Z"
creator = "spheniscine"
source_ids = ["valsi=29800"]

[[etymology]]
id = 899
lang = "en"
author = "spheniscine"
updated = "2015-09-05T04:09:36Z"
content = "Lojban {na'i} + {jitfa}"
