word = "xu'u'i"
type = "experimental cmavo"
rafsi = []
selmaho = []
created = "2014-06-13T07:38:22Z"
creator = "krtisfranks"
source_ids = ["valsi=26855"]

[[etymology]]
id = 469
lang = "en"
author = "krtisfranks"
updated = "2014-06-13T07:44:27Z"
content = "Onomatopoeic: hoo-hoo-heeeeeee!"
